adding rock 3a install

diff --git a/MANET/provisioning/firstrun.sh.template b/MANET/provisioning/firstrun.sh.template
--- a/MANET/provisioning/firstrun.sh.template
+++ b/MANET/provisioning/firstrun.sh.template
@@ -148,6 +148,12 @@ elif [ "__HARDWARE_MODEL__" = "rpi4" ]; then
 		else
 		echo "Filesystem has room (${USAGE_PERCENT}%), skipping expansion."
 		fi
+elif [ "__HARDWARE_MODEL__" = "r3a" ]; then
+		echo "Applying Raxda Rock 3A specific settings..."
+#		wget -q https://github.com/very-srs/MANET/raw/refs/heads/main/MANET/install_packages/cm4-install.tar.gz -O /root/morse-pi-install.tar.gz || {
+		wget -q  https://www.colorado-governor.com/manet/r3a-install.tar.gz -O /root/morse-pi-install.tar.gz || {
+				echo "ERROR: Failed to download Rock 3a install package"
+				exit 1
 fi
 
 #
