updating for armbian

diff --git a/MANET/provisioning/firstrun.sh.template b/MANET/provisioning/firstrun.sh.template
--- a/MANET/provisioning/firstrun.sh.template
+++ b/MANET/provisioning/firstrun.sh.template
@@ -125,7 +125,6 @@ if [ "__HARDWARE_MODEL__" = "rpi5" ]; then
 		touch /var/lib/expand-root-done
 elif [ "__HARDWARE_MODEL__" = "rpi4" ]; then
 		echo "Applying RPi 4 specific settings..."
-#		wget -q https://github.com/very-srs/MANET/raw/refs/heads/main/MANET/install_packages/cm4-install.tar.gz -O /root/morse-pi-install.tar.gz || {
 		wget -q  https://www.colorado-governor.com/manet/cm4-install.tar.gz -O /root/morse-pi-install.tar.gz || {
 				echo "ERROR: Failed to download rpi4 package"
 				exit 1
@@ -148,6 +147,13 @@ elif [ "__HARDWARE_MODEL__" = "rpi4" ]; then
 		else
 		echo "Filesystem has room (${USAGE_PERCENT}%), skipping expansion."
 		fi
+		touch /var/lib/expand-root-done
+elif [ "__HARDWARE_MODEL__" = "r3a" ]; then
+		echo "Applying Rock 3A specific settings..."
+		wget -q https://www.colorado-governor.com/manet/r3a-install.tar.gz -O /root/morse-pi-install.tar.gz || {
+				echo "ERROR: Failed to download Rock 3A package"
+				exit 1
+		}
 fi
 
 #
@@ -178,12 +184,33 @@ apt install -y ipcalc nmap lshw tcpdump net-tools nftables wireless-tools iperf3
 # mesh tools
 tar -zxf /root/morse-pi-install.tar.gz -C /
 
-cd /root/morse-firmware
-sudo cp firmware/mm8108*.bin /lib/firmware/morse/
-sudo cp bcf/morsemicro/*.bin /lib/firmware/morse/
-sudo cp bcf/azurewave/*.bin /lib/firmware/morse/
-sudo cp bcf/netprisma/*.bin /lib/firmware/morse/
-sudo cp bcf/quectel/*.bin /lib/firmware/morse/
+# Platform-specific post-extraction steps
+if [ "__HARDWARE_MODEL__" = "r3a" ]; then
+	# Unpack the r3a kernel
+	cd /root
+	dpkg -i *.deb
+
+	# Add the morse firmware
+	cd /root/morse-firmware
+	cp firmware/mm8108*.bin /lib/firmware/morse/
+	cp bcf/morsemicro/*.bin /lib/firmware/morse/
+	cp bcf/azurewave/*.bin /lib/firmware/morse/
+	cp bcf/netprisma/*.bin /lib/firmware/morse/
+	cp bcf/quectel/*.bin /lib/firmware/morse/
+
+	# Disable predictable interface names for Armbian
+	sed -i '/^extraargs=/ s/$/ net.ifnames=0/' /boot/armbianEnv.txt
+	
+	cd /root
+else
+	# RPi-specific firmware
+	cd /root/morse-firmware
+	sudo cp firmware/mm8108*.bin /lib/firmware/morse/
+	sudo cp bcf/morsemicro/*.bin /lib/firmware/morse/
+	sudo cp bcf/azurewave/*.bin /lib/firmware/morse/
+	sudo cp bcf/netprisma/*.bin /lib/firmware/morse/
+	sudo cp bcf/quectel/*.bin /lib/firmware/morse/
+fi
 
 
 # Installed but not being used now
@@ -210,6 +237,9 @@ systemctl mask dev-zram0.device > /dev/null 2>&1
 
 
 
+# Load batman-adv module at boot
+echo "batman_adv" > /etc/modules-load.d/batman.conf
+
 # Load modules at boot
 cat << EOF > /etc/modules-load.d/morse.conf
 mac80211
@@ -230,65 +260,15 @@ EOF
 # this is probably redundant, and should be done in radio-setup.sh with a variable for the wlan interface
 cat << EOF > /etc/wpa_supplicant-wlan2-s1g.conf
 country=US
-ctrl_interface=/var/run/wpa_supplicant_s1g
-sae_pwe=1
-max_peer_links=10
-mesh_fwding=0
-network={
-    ssid=$mesh_ssid
-    key_mgmt=SAE
-    mode=5
-    channel=12
-    op_class=71
-    country="US"
-    s1g_prim_chwidth=1
-    s1g_prim_1mhz_chan_index=3
-    dtim_period=1
-    mesh_rssi_threshold=-85
-    dot11MeshHWMPRootMode=0
-    dot11MeshGateAnnouncements=0
-    mbca_config=1
-    mbca_min_beacon_gap_ms=25
-    mbca_tbtt_adj_interval_sec=60
-    dot11MeshBeaconTimingReportInterval=10
-    mbss_start_scan_duration_ms=2048
-    mesh_beaconless_mode=0
-    mesh_dynamic_peering=0
-    sae_password=$mesh_key
-    pairwise=CCMP
-    ieee80211w=2
-    beacon_int=1000
-}
 EOF
 
-echo "batman-adv" > /etc/modules-load.d/batman.conf
-
-# Disable the default wpa_supplicant service
-systemctl disable wpa_supplicant.service > /dev/null 2>&1
-
-# Set hostname, make unique by ethernet mac addr (last 4)
-hostnamectl hostname radio-$HOST_MAC
-sed -i "s/raspberrypi/radio-${HOST_MAC}/g" /etc/hosts
-echo "Hostname set"
-
-# Set regulatory region  (default will be US)
-echo options cfg80211 ieee80211_regdom=$REG > /etc/modprobe.d/wifi-regdom.conf
-echo "Set wifi regulatory domain to $REG"
-
-#turn on packet forwarding
+# More kernel tweaks
 cat << EOF > /etc/sysctl.d/99-mesh.conf
-# IPv4 forwarding for mesh
-net.ipv4.ip_forward=1
+# IPv4 forwarding
 net.ipv4.conf.all.forwarding=1
 net.ipv4.conf.default.forwarding=1
 
-# IPv4 multicast forwarding
-net.ipv4.conf.all.mc_forwarding=1
-net.ipv4.conf.default.mc_forwarding=1
-net.ipv4.conf.bat0.mc_forwarding=1
-net.ipv4.conf.br0.mc_forwarding=1
-
-# IPv6 forwarding for mesh
+# IPv6 forwarding
 net.ipv6.conf.all.forwarding=1
 net.ipv6.conf.default.forwarding=1
 
@@ -433,7 +413,8 @@ echo "Ethernet templates created"
 
 
 #  Set up the node firewall to accept just about everything and to forward traffic out the
-#  ethernet interface.  This can just be set and forgotten and will only make a difference
+#  ethernet interface.
+#  This can just be set and forgotten and will only make a difference
 #  when the node is plugged into a network
 
 #  Should consider moving this to radio setup to take advantage of better interface detection
@@ -540,7 +521,8 @@ systemctl enable radvd
 
 # Attempt to sync network time at boot
 # Uses data from Alfred to look for any NTP servers (a gw that has
-# sync'd its time from the internet) on the mesh.  It picks the
+# sync'd its time from the internet) on the mesh.
+# It picks the
 # one with the best transmission quality, does a time sync with it,
 # and then disables chrony to prevent excess network traffic
 cat << EOF > /etc/systemd/system/one-shot-time-sync.service
